### ISSUE TITLE
Unhardcode ipaddr and port

### ISSUE THREAD

**Issue by phrohdoh** [dylanmckay/mdns#2]
https://docs.rs/mdns/0.1.4/src/mdns/.cargo/registry/src/github.com-1ecc6299db9ec823/mdns-0.1.4/src/mdns.rs.html#16-17

**Comment by dylanmckay** [comment]
Nice catch!

I must've left this in when I was trying to discover my Chromecast.

**Comment by dylanmckay** [comment]
Looking into this more, it looks like all IPv4 mDNS queries join this multicast group.

From the [Wikipedia page](https://en.wikipedia.org/wiki/Multicast_DNS):

> The mDNS Ethernet frame is a multicast UDP packet to:
>
> MAC address 01:00:5E:00:00:FB (for IPv4) or 33:33:00:00:00:FB (for IPv6)
> IPv4 address 224.0.0.251 or IPv6 address FF02::FB
> UDP port 5353

This address should be the only one used as far as I can understand.

**Comment by phrohdoh** [comment]
For example, unless I am misunderstanding [this code](https://github.com/Parrot-Developers/Samples/blob/master/Unix/BebopPilotingNewAPI/BebopPiloting.c#L66-L67), my device's ip is 192.168.42.1 with a port 44444 for mDNS discovery.

This may be unnecessary (it is very probable that I am incorrect), in which case this should be closed.

For reference this is the project I'm working on: https://github.com/Phrohdoh/arini-discovery/blob/master/src/bin/main.rs

**Comment by dylanmckay** [comment]
I am also very new to mDNS but this was what I know so far:

To send an mDNS query, you open up a socket to one of your local network interfaces (e.g. `192.168.1.1`). After that, you add your socket to a multicast group with a multicast IP address (e.g. `224.0.0.251`). All multicast IP addresses are in the `224.x.x.x` range (or something like that, I've forgotten the actual range).

To then multicast DNS packets, you just send the DNS packets to `192.168.1.1` and they automatically get multicasted to all devices on the network.

If you take a look at [this](https://github.com/Parrot-Developers/libARDiscovery/blob/master/JNI/java/com/parrot/arsdk/ardiscovery/mdnssdmin/MdnsSdMin.java#L130) source file in the `libARDiscovery` library, it also uses the same mDNS multicast address as we do (although of course, that's a Java source and only related to the file you linked).

If your device's IP is `192.168.42.1`, that is not a multicast DNS address and it is the address of your actual device. You don't need to perform discovery if you already have the IP.

I think what you want to do if you want to be able to discover any "ARDiscovery" device :

* Perform mDNS discovery using the default IP that is hardcoded. Make sure you have the correct service names
* You can then just grab the IP that is discovered

This is of course assuming that the ARDiscovery protocol doesn't use a weird version of mDNS or something. If there is actually a usecase for using a different multicast IP, I'm super happy to make it possible.

What you could do if you need help:

Download [WireShark](https://www.wireshark.org), start a packet capturing session and filter to `mdns`. Run the official ARDiscovery and make sure it picks up the device. Send me the packet dump and I can take a look.

Your project sounds really cool by the way!

**Comment by dylanmckay** [comment]
Also, try adding `.local` to the end of your service type strings like `_arsdk-0901`

**Comment by phrohdoh** [comment]
Here is a response I got using `dns-sd`:

```
tmba:bebop thill $ dns-sd -B _arsdk-090c._udp
Browsing for _arsdk-090c._udp
DATE: ---Sun 04 Dec 2016---
11:58:09.238  ...STARTING...
Timestamp     A/R    Flags  if Domain               Service Type         Instance Name
11:58:09.494  Add        2   4 local.               _arsdk-090c._udp.    Bebop2-008234

tmba:bebop thill $ dns-sd -L Bebop2-008234 _arsdk-090c._udp
Lookup Bebop2-008234._arsdk-090c._udp.local
DATE: ---Sun 04 Dec 2016---
12:00:56.217  ...STARTING...
12:00:56.467  Bebop2-008234._arsdk-090c._udp.local. can be reached at Bebop2-008234.local.:44444 (interface 4)
\{\"device_id\":\"PI040384AG6G008234\"\}
```

Here is my capture (had to zip it up to please github) and some data I pulled out of it (using the display filter `tcp.dstport == 44444`):
[bebop2-wireshark-capture.pcapng.zip](https://github.com/dylanmckay/mdns/files/629590/bebop2-wireshark-capture.pcapng.zip)

```
0000   a0 14 3d c6 75 f1 9c f3 87 d1 24 c8 08 00 45 02  ..=.u.....$...E.
0010   01 26 f9 b1 40 00 40 06 6a 79 c0 a8 2a 53 c0 a8  .&..@.@.jy..*S..
0020   2a 01 e2 99 ad 9c 9a a6 64 c0 0b 73 75 67 80 18  *.......d..sug..
0030   10 15 8e d5 00 00 01 01 08 0a 3a 0c 57 9d 00 00  ..........:.W...
0040   e5 f2 7b 20 22 71 6f 73 5f 6d 6f 64 65 22 3a 20  ..{ "qos_mode": 
0050   31 2c 20 22 64 32 63 5f 70 6f 72 74 22 3a 20 34  1, "d2c_port": 4
0060   39 33 30 32 2c 20 22 61 72 73 74 72 65 61 6d 32  9302, "arstream2
0070   5f 63 6c 69 65 6e 74 5f 73 74 72 65 61 6d 5f 70  _client_stream_p
0080   6f 72 74 22 3a 20 36 34 33 36 38 2c 20 22 61 72  ort": 64368, "ar
0090   73 74 72 65 61 6d 32 5f 63 6c 69 65 6e 74 5f 63  stream2_client_c
00a0   6f 6e 74 72 6f 6c 5f 70 6f 72 74 22 3a 20 36 34  ontrol_port": 64
00b0   36 31 35 2c 20 22 61 72 73 74 72 65 61 6d 32 5f  615, "arstream2_
00c0   73 75 70 70 6f 72 74 65 64 5f 6d 65 74 61 64 61  supported_metada
00d0   74 61 5f 76 65 72 73 69 6f 6e 22 3a 20 31 2c 20  ta_version": 1, 
00e0   22 63 6f 6e 74 72 6f 6c 6c 65 72 5f 6e 61 6d 65  "controller_name
00f0   22 3a 20 22 44 45 46 41 55 4c 54 5f 53 44 4b 5f  ": "DEFAULT_SDK_
0100   43 4f 4e 54 52 4f 4c 4c 45 52 22 2c 20 22 63 6f  CONTROLLER", "co
0110   6e 74 72 6f 6c 6c 65 72 5f 74 79 70 65 22 3a 20  ntroller_type": 
0120   22 44 45 46 41 55 4c 54 5f 53 44 4b 5f 54 59 50  "DEFAULT_SDK_TYP
0130   45 22 20 7d                                      E" }

{ "qos_mode": 1, "d2c_port": 49302, "arstream2_client_stream_port": 64368, "arstream2_client_control_port": 64615, "arstream2_supported_metadata_version": 1, "controller_name": "DEFAULT_SDK_CONTROLLER", "controller_type": "DEFAULT_SDK_TYPE" }{ "status": 0, "c2d_port": 54321, "c2d_update_port": 51, "c2d_user_port": 21, "qos_mode": 1, "arstream2_server_stream_port": 5004, "arstream2_server_control_port": 5005 }.
```

This lead me to a generated C file that contains:
```
/**
 * @brief JSON strings for UDP ports extraction
 */
#define ARDISCOVERY_CONNECTION_JSON_STATUS_KEY                              "status"
#define ARDISCOVERY_CONNECTION_JSON_C2DPORT_KEY                             "c2d_port"
#define ARDISCOVERY_CONNECTION_JSON_D2CPORT_KEY                             "d2c_port"
#define ARDISCOVERY_CONNECTION_JSON_ARSTREAM_FRAGMENT_SIZE_KEY              "arstream_fragment_size"
#define ARDISCOVERY_CONNECTION_JSON_ARSTREAM_FRAGMENT_MAXIMUM_NUMBER_KEY    "arstream_fragment_maximum_number"
#define ARDISCOVERY_CONNECTION_JSON_ARSTREAM_MAX_ACK_INTERVAL_KEY           "arstream_max_ack_interval"
#define ARDISCOVERY_CONNECTION_JSON_CONTROLLER_TYPE_KEY                     "controller_type"
#define ARDISCOVERY_CONNECTION_JSON_CONTROLLER_NAME_KEY                     "controller_name"
#define ARDISCOVERY_CONNECTION_JSON_DEVICE_ID_KEY                           "device_id"
#define ARDISCOVERY_CONNECTION_JSON_C2D_UPDATE_PORT_KEY                     "c2d_update_port"
#define ARDISCOVERY_CONNECTION_JSON_C2D_USER_PORT_KEY                       "c2d_user_port"
#define ARDISCOVERY_CONNECTION_JSON_SKYCONTROLLER_VERSION                   "skycontroller_version"
#define ARDISCOVERY_CONNECTION_JSON_FEATURES_KEY                            "features"
#define ARDISCOVERY_CONNECTION_JSON_QOS_MODE_KEY                            "qos_mode"

/**
 * ARStream2 specific keys
 */
#define ARDISCOVERY_CONNECTION_JSON_ARSTREAM2_CLIENT_STREAM_PORT_KEY          "arstream2_client_stream_port"
#define ARDISCOVERY_CONNECTION_JSON_ARSTREAM2_CLIENT_CONTROL_PORT_KEY         "arstream2_client_control_port"
#define ARDISCOVERY_CONNECTION_JSON_ARSTREAM2_SERVER_STREAM_PORT_KEY          "arstream2_server_stream_port"
#define ARDISCOVERY_CONNECTION_JSON_ARSTREAM2_SERVER_CONTROL_PORT_KEY         "arstream2_server_control_port"
#define ARDISCOVERY_CONNECTION_JSON_ARSTREAM2_MAX_PACKET_SIZE_KEY             "arstream2_max_packet_size"
#define ARDISCOVERY_CONNECTION_JSON_ARSTREAM2_MAX_LATENCY_KEY                 "arstream2_max_latency"
#define ARDISCOVERY_CONNECTION_JSON_ARSTREAM2_MAX_NETWORK_LATENCY_KEY         "arstream2_max_network_latency"
#define ARDISCOVERY_CONNECTION_JSON_ARSTREAM2_MAX_BITRATE_KEY                 "arstream2_max_bitrate"
#define ARDISCOVERY_CONNECTION_JSON_ARSTREAM2_SUPPORTED_METADATA_VERSION_KEY  "arstream2_supported_metadata_version"
#define ARDISCOVERY_CONNECTION_JSON_ARSTREAM2_PARAMETER_SETS_KEY              "arstream2_parameter_sets"

/**
 * Audio specific keys
 */
#define ARDISCOVERY_CONNECTION_JSON_AUDIO_CODEC_VERSION_KEY                 "audio_codec"

/**
 * Audio specific keys
 */
#define ARDISCOVERY_CONNECTION_JSON_AUDIO_CODEC_VERSION_KEY                 "audio_codec"
```

I am not sure what exactly needs to be included in the service name to perform a successful discovery.

`_arsdk-090c`, `_arsdk-090c._udp`, and `_arsdk-090c._udp.local` yield "network is unreachable" while `_arsdk-090c._udp.local.` returns an InvalidQuery error.

I will keep working on getting a connection but would very much welcome help, but this is becoming unrelated to your project rather quickly, so for that I apologize.

If you are interested in helping I'm often on #rust and #rust-offtopic (or the conversation could move to https://github.com/Phrohdoh/arini-discovery/issues/1).

**Comment by dylanmckay** [comment]
> I will keep working on getting a connection but would very much welcome help, but this is becoming unrelated to your project rather quickly, so for that I apologize.

No problems!
