### ISSUE TITLE
Support IPv6

### ISSUE THREAD

**Issue by dylanmckay** [dylanmckay/mdns#3]

**Comment by dylanmckay** [comment]
Currently works via `AAAA` records.

**Comment by Kilobyte22** [comment]
@dylanmckay i vote to reopen this issue. While you can resolve AAAA records, you cannot actually send the MDNS requests over IPv6. I have a proprietary device here which does not support IPv4 which makes this library unusable for me.

I have actually patched the current version locally to work, however with IPv6 there are some differences. Multiple Interfaces can have the exact same address when using link-local addresses, and mDNS does use link-local addresses with IPv6. Therefore you can't use an IP address to specify the interface, but have to use a numeric ID. Furthermore it is not possible to send out packets to the any interface. So in total I would say, it's not trivial.
