### ISSUE TITLE
Support for TXT Records in service

### ISSUE THREAD

**Issue by soundprojects** [dylanmckay/mdns#9]
Hi is it possible to add support for retrieving TXT records and the hostname in the discovered services?

**Comment by dylanmckay** [comment]
It looks like this is already implemented [here](https://github.com/dylanmckay/mdns/blob/2a256cd576a5a8f1a4ee73bb7ba5fee81a7dd9dc/src/response.rs#L99).

[Here](https://docs.rs/mdns/0.2.3/mdns/enum.RecordKind.html#variant.TXT) is the `RecordKind` for `TXT` records.
